layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects: 
     -  GetADelivery
    
social_media: 
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: gregorywalfish
  # keybase: your_username
  linkedin: gregorywalfish
  # mastodon: your_username
  medium: gregorywalfish
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: gregorywalfish
  # unsplash: your_username
  # vk: your_username
  # website: https://backdoormtl.com/
  # youtube: your_username

topics:
  - name: Backdoor MTL
    web_url: https://backdoormtl.com/
    image_url: https://scontent.fymy1-2.fna.fbcdn.net/v/t1.0-9/82936372_1191194661083877_2942479307055824896_n.png?_nc_cat=110&ccb=2&_nc_sid=09cbfe&_nc_ohc=u_BeQTsQkLIAX-tNJpD&_nc_ht=scontent.fymy1-2.fna&oh=ed1214b11852f88052a5c79beea8ea03&oe=5FD5EFA8
  - name: Paysafe

  #- name: Sass
    web_url: https://www.paysafe.com/na-en/
    image_url: https://res-4.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco/txzyv21bswexrrzztlt9
